import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Suzal",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
      isSeller: true,
      seller: {
        name: "Nike",
        logo: "/images/p1.jpg",
        description: "best seller",
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Nike Smart Watch",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Adidas Smart Watch",
      category: "Watch",
      image: "/images/p1.jpg",
      price: 100,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Dell Laptop",
      category: "Laptop",
      image: "/images/p1.jpg",
      price: 220,
      countInStock: 0,
      brand: "Intel",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Acer Laptop",
      category: "Laptop",
      image: "/images/p1.jpg",
      price: 78,
      countInStock: 15,
      brand: "Intel",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "Samsung Mobile",
      category: "Mobile",
      image: "/images/p1.jpg",
      price: 65,
      countInStock: 5,
      brand: "Samsung",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "MI X3 pro",
      category: "Mobile",
      image: "/images/p1.jpg",
      price: 139,
      countInStock: 12,
      brand: "MI",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};
export default data;
